-- SPDX-FileCopyrightText: <text>Copyright 2025-2026 Arm Limited and/or its
-- affiliates <open-source-office@arm.com></text>
-- SPDX-License-Identifier: MIT

-- This lua script is a pandoc writer that generates confluence XHTML storage format.
-- It is based on the default HTML writer, but with modifications to suit confluence.
-- It supports a subset of pandoc's markdown features, and is intended to be used
-- with pandoc's --to=confluence option.
-- It also supports some custom metadata fields for confluence pages.
-- See https://pandoc.org/MANUAL.html#extension-confluence for details.
-- See https://developer.atlassian.com/server/confluence/confluence-storage-format/ for details.
-- Note: This writer does not support all features of confluence, and may produce
-- invalid or incomplete output in some cases.
-- Use at your own risk.
local function add_tools_root_to_package_path()
  local script = PANDOC_SCRIPT_FILE
  if not script then
    return
  end
  local script_dir = script:match("(.*/)")
  if not script_dir then
    return
  end
  local tools_root = script_dir .. ".."
  package.path = table.concat({
    tools_root .. "/?.lua",
    tools_root .. "/?/init.lua",
    package.path,
  }, ";")
end

add_tools_root_to_package_path()

local logging = require 'theme/logging/logging'

-- Escape special HTML characters
local function escape_html(text)
    local entities = {
        ["&"] = "&amp;",
        ["<"] = "&lt;",
        [">"] = "&gt;",
    }
    return text:gsub("[&<>]", entities)
end

Template = (''
    .. '<!-- This file is generated by pandoc. Do not edit! -->\n'
    .. '<!-- Title: $title$ -->\n'
    .. '<ac:layout>\n'
    .. '<ac:layout-section ac:type="single">\n'
    .. '<ac:layout-cell>\n'
    .. '<p>Author: $author$ (<ac:link><ri:user ri:userkey="8a81eaf24e3f2407014e3f3972f403f9" /></ac:link>)<br />\n'
    .. '$for(copyright)$'
    .. '  $copyright.SPDX-FileCopyrightText$<br />\n'
    .. '$endfor$'
    .. 'Last updated: $LAST_UPDATED$<br />\n'
    .. 'Source: $src$<br />\n'
    .. 'Version: $VERSION$</p>\n'
    -- .. '<p><ac:structured-macro ac:name="toc" ac:schema-version="1"><ac:parameter ac:name="maxLevel">2</ac:parameter><ac:parameter ac:name="style">none</ac:parameter></ac:structured-macro></p>\n'
    .. '$body$ '
    .. '</ac:layout-cell>\n'
    .. '</ac:layout-section>\n'
    .. '</ac:layout>\n');

Writer = pandoc.scaffolding.Writer

Writer.Inline.Str = function(str)
    return escape_html(str.text)
end

Writer.Inline.Space = function(space)
    return " "
end

local function create_anchor(id)
    return string.format(
        '<ac:structured-macro ac:name="anchor" ac:schema-version="1"><ac:parameter ac:name="">%s</ac:parameter></ac:structured-macro>',
        escape_html(id))
end

Writer.Block.Header = function(header)
    local tag = "h" .. header.level
    local attr = pandoc.utils.stringify(header.attr.identifier) ~= "" and
        ' id="' .. escape_html(pandoc.utils.stringify(header.attr.identifier)) .. '"' or ""
    local classes = #header.attr.classes > 0 and
        ' class="' .. table.concat(header.attr.classes, " ") .. '"' or ""
    local content = pandoc.utils.stringify(header.content)
    local anchor = create_anchor(pandoc.utils.stringify(header.attr.identifier))
    local section_number = header.attr.attributes["section-number"]
    if section_number then
        content = section_number .. " " .. content
    end
    return string.format("%s<%s%s%s>%s</%s>\n", anchor, tag, attr, classes, escape_html(content), tag)
end

Writer.Block.Para = function(para)
    -- iterate over para.content to handle inlines properly
    return { "<p>", Writer.Inlines(para.content), "</p>\n" }
end

Writer.Block.Plain = function(plain)
    return { "", Writer.Inlines(plain.content), "\n" }
end

Writer.Block.DefinitionList = function(deflist)
    local items = {}
    for _, item in ipairs(deflist.content) do
        local term = Writer.Inlines(item[1])
        local definitions = {}
        for _, def in ipairs(item[2]) do
            table.insert(definitions, Writer.Blocks(def))
        end
        table.insert(items, string.format("<dt>%s</dt>\n<dd>%s</dd>\n", term, table.concat(definitions, "\n")))
    end
    return string.format("<dl>\n%s\n</dl>\n", table.concat(items, "\n"))
end

Writer.Inline.Code = function(code)
    local attr = pandoc.utils.stringify(code.attr.identifier) ~= "" and
        ' id="' .. escape_html(pandoc.utils.stringify(code.attr.identifier)) .. '"' or ""
    local classes = #code.attr.classes > 0 and
        ' class="' .. table.concat(code.attr.classes, " ") .. '"' or ""
    local content = escape_html(code.text)
    return string.format("<code%s%s>%s</code>", attr, classes, content)
end

Writer.Inline.Quoted = function(quoted)
    local quote_type = quoted.quote_type == "Single" and "‘" or "“"
    local end_quote_type = quoted.quote_type == "Single" and "’" or "”"
    local content = pandoc.utils.stringify(quoted.content)
    return string.format("%s%s%s", quote_type, escape_html(content), end_quote_type)
end

Writer.Inline.SoftBreak = function()
    return " "
end

Writer.Inline.LineBreak = function()
    return "<br/>"
end

Writer.Inline.RawInline = function(raw)
    if raw.format:match 'html' then
        return raw.text
    end
    return ""
end

Writer.Inline.Emph = function(emph)
    local content = Writer.Inlines(emph.content)
    return { "<em>", content, "</em>" }
end

Writer.Inline.Superscript = function(sup)
    local content = Writer.Inlines(sup.content)
    return { "<sup>", content, "</sup>" }
end

Writer.Inline.Strong = function(strong)
    local content = Writer.Inlines(strong.content)
    return {"<strong>", content, "</strong>"}
end

Writer.Inline.Link = function(link)
    local attr = pandoc.utils.stringify(link.attr.identifier) ~= "" and
        ' id="' .. escape_html(pandoc.utils.stringify(link.attr.identifier)) .. '"' or ""
    local classes = #link.attr.classes > 0 and
        ' class="' .. table.concat(link.attr.classes, " ") .. '"' or ""
    local content = Writer.Inlines(link.content)
    local url = escape_html(link.target)
    -- if the target is to an anchor in the same document, use a confluence anchor link
    if url:sub(1, 1) == "#" then
        return string.format('<ac:link ac:anchor="%s"><ac:link-body>%s</ac:link-body></ac:link>',
            escape_html(url:sub(2)), content)
    end
    return string.format('<a href="%s"%s%s>%s</a>', url, attr, classes, content)
end

Writer.Inline.Cite = function(cite)
    local content = Writer.Inlines(cite.content)
    return string.format("<cite>%s</cite>", content)
end

local note_counter = 0

Writer.Inline.Note = function(note)
    local content = Writer.Blocks(note.content)
    note_counter = note_counter + 1
    local note_indicator = string.format('<sup>[%d]</sup>', note_counter)
    return {
        note_indicator,
        '\n<ac:structured-macro ac:name="float" ac:schema-version="1">',
        '<ac:parameter ac:name="side">right</ac:parameter>',
        '<ac:parameter ac:name="width">150px</ac:parameter>',
        '<ac:rich-text-body>',
          '\n  <ac:structured-macro ac:name="bgcolor" ac:schema-version="1">',
          '<ac:parameter ac:name="color">#FFFCF2</ac:parameter>',
          '<ac:parameter ac:name="atlassian-macro-output-type">INLINE</ac:parameter>',
            '<ac:rich-text-body>\n',
            note_indicator,
            content,
            '\n  </ac:rich-text-body>',
          '</ac:structured-macro>',
        '\n</ac:rich-text-body>',
        '</ac:structured-macro>'
    }
end

local function get_anchor_if_id(el)
    if pandoc.utils.stringify(el.attr.identifier) ~= "" then
        local anchor = create_anchor(pandoc.utils.stringify(el.attr.identifier))
        return anchor
    else
        return ""
    end
end

local function process_specific_spans(span)
    local content = pandoc.utils.stringify(span.content)
    local anchor = get_anchor_if_id(span)
    if #span.attr.classes > 0 then
        for _, class in ipairs(span.attr.classes) do
            -- TODO: do I need to do special processing for index spans?
            --if class == "index" then
            --    -- Extract the entry from the content
            --    local entry = content:match('entry="(.-)"')
            --    if entry then
            --        return string.format(
            --            '<ac:structured-macro ac:name="index-term"><ac:parameter ac:name="term">%s</ac:parameter></ac:structured-macro>',
            --            escape_html(entry))
            --    end
            if class == "todo" then
                return anchor .. string.format(
                    '<span style="background-color: yellow; color: red; font-weight: bold;">TODO: %s</span>',
                    escape_html(content))
            elseif class == "index-entry" then
                return {anchor, Writer.Inlines(span.content), '<br/>'} -- let the content be processed normally
            elseif class == "index-entry-indentation" then
                return '&nbsp;&nbsp;&nbsp;&nbsp;' .. anchor .. Writer.Inlines(span.content) -- indent with non-breaking spaces
            end
        end
    end
    return nil
end

Writer.Inline.Span = function(span)
    local specific = process_specific_spans(span)
    if specific then
        return specific
    end
    -- Default span processing
    local attr = pandoc.utils.stringify(span.attr.identifier) ~= "" and
        ' id="' .. escape_html(pandoc.utils.stringify(span.attr.identifier)) .. '"' or ""
    local classes = #span.attr.classes > 0 and
        ' class="' .. table.concat(span.attr.classes, " ") .. '"' or ""
    local content = Writer.Inlines(span.content) --pandoc.utils.stringify(span.content)
    local result = get_anchor_if_id(span)
    --logging.error("Span content: " .. content)
    --logging.error("Span attr: " .. attr)
    --logging.error("Span classes: " .. classes)
    result = result .. string.format("<span%s%s>%s</span>", attr, classes, content)
    return result
end

local function split_literal(str, sep)
  local parts = {}
  local plain_sep = str:find(sep, 1, true) and sep or sep  -- true flag = plain find
  local last = 1
  local i, j = str:find(sep, last, true)
  while i do
    table.insert(parts, str:sub(last, i-1))
    last = j + 1
    i, j = str:find(sep, last, true)
  end
  table.insert(parts, str:sub(last))
  return parts
end

local function process_specific_divs(div)
    local anchor = get_anchor_if_id(div)
    if #div.attr.classes > 0 then
        for _, class in ipairs(div.attr.classes) do
            if class == "index-entry-list" then
                -- todo put half of entries in one cell and half in the other
                -- just split the list of elements in half for now and assumes that
                -- works well enough
                local content = pandoc.layout.render(Writer.Blocks(div.content))
                --logging.error("Index entry list content: ", content)
                -- content is a strings.
                -- First, in a hack, remove '<p></p>' from content, and replace it with <br/>
                content = content:gsub("<p></p>", "<br/>")
                -- now split content on <br/> tags
                local entries = split_literal(content, "<br/>")
                local half = math.ceil(#entries / 2)
                -- logging.error("Entries: ", table.concat(entries, "|"))
                -- logging.error("Half: ", half)
                -- logging.error("Left entries: ", table.concat(entries, 1, half), "|")
                -- logging.error("Right entries: ", table.concat(entries, half + 1), "|")
                -- now create left and right content
                local left_content = table.concat(entries, "<br/>", 1, half)
                local right_content = table.concat(entries, "<br/>", half + 1)
                return {
                    anchor,
                    '</ac:layout-cell>\n',
                    '</ac:layout-section>\n',
                    '<ac:layout-section ac:type="two_equal">\n',
                    '<ac:layout-cell>\n',
                    '<ac:structured-macro ac:name="panel">\n',
                    '<ac:parameter ac:name="bgColor">#EFEFEF</ac:parameter>\n',
                    '<ac:rich-text-body>\n',
                    left_content,
                    '</ac:rich-text-body>\n',
                    '</ac:structured-macro>\n',
                    '</ac:layout-cell>\n',
                    '<ac:layout-cell>\n',
                    '<ac:structured-macro ac:name="panel">\n',
                    '<ac:parameter ac:name="bgColor">#EFEFEF</ac:parameter>\n',
                    '<ac:rich-text-body>\n',
                    right_content,
                    '</ac:rich-text-body>\n',
                    '</ac:structured-macro>\n',
                    '</ac:layout-cell>\n',
                    '</ac:layout-section>\n',
                    '<ac:layout-section ac:type="single">\n<ac:layout-cell>\n',
                }
            elseif class == "TODO" then
                local content = pandoc.utils.stringify(div.content)
                return anchor .. string.format(
                    '<div style="background-color: yellow; color: red; font-weight: bold;">TODO: %s</div>',
                    escape_html(content))
            --elseif class == "csl-entry" then
            --    return { '\n<p>', Writer.Blocks(div.content), '</p>' }
            elseif class == "csl-entry" then
                return {
                    anchor,
                    '<ac:structured-macro ac:name="panel">\n',
                    '  <ac:parameter ac:name="bgColor">#EFEFEF</ac:parameter>\n',
                    '  <ac:rich-text-body>\n',
                    Writer.Blocks(div.content),
                    '  </ac:rich-text-body>\n',
                    '</ac:structured-macro>\n'}
                -- return { '\n<div><br/>', anchor, Writer.Blocks(div.content), '</div>\n' }
            elseif class == "smaller" then
                return {
                    anchor,
                    '<ac:structured-macro ac:name="expand" ac:schema-version="1"><ac:rich-text-body>',
                    Writer.Blocks(div.content),
                    '</ac:rich-text-body></ac:structured-macro>',
                }
            elseif class == "definition" or class == "example" then
                return {
                    anchor,
                    '<ac:structured-macro ac:name="panel" ac:schema-version="1">',
                    '<ac:parameter ac:name="title">',
                    div.attr.attributes["caption"],
                    '</ac:parameter>',
                    '<ac:rich-text-body>',
                    Writer.Blocks(div.content),
                    '</ac:rich-text-body>',
                    '</ac:structured-macro>',
                }
            elseif class == "toc-list" then
                -- handled in Div function below
                return {
                    anchor,
                    '<div style="margin-left: 40px;">',
                    Writer.Blocks(div.content),
                    '</div>\n'
                }
            end
        end
    end
    return nil
end

Writer.Block.Div = function(div)
    local specific = process_specific_divs(div)
    if specific then
        return specific
    end
    local attr = pandoc.utils.stringify(div.attr.identifier) ~= "" and
        ' id="' .. escape_html(pandoc.utils.stringify(div.attr.identifier)) .. '"' or ""
    local classes = #div.attr.classes > 0 and
        ' class="' .. table.concat(div.attr.classes, " ") .. '"' or ""
    local content = Writer.Blocks(div.content) --pandoc.utils.stringify(div.content)
    local result = get_anchor_if_id(div)
    result = result .. string.format("<div%s%s>\n%s\n</div>\n", attr, classes, content)
    return result
end

-- <p style="margin-left: 40.0px;">section 1</p>
-- <p style="margin-left: 80.0px;"><span style="letter-spacing: 0.0px;">section 2</span></p>
-- <p style="margin-left: 40.0px;">section 3</p>
Writer.Block.BulletList = function(list)
    local items = {}
    for _, item in ipairs(list.content) do
        local item_content = Writer.Blocks(item) -- pandoc.utils.stringify(item)
        table.insert(items, string.format("<li>%s</li>", item_content))
    end
    return string.format("<ul>\n%s\n</ul>\n", table.concat(items, "\n"))
end

Writer.Block.OrderedList = function(list)
    local items = {}
    for _, item in ipairs(list.content) do
        local item_content = Writer.Blocks(item) -- pandoc.utils.stringify(item)
        table.insert(items, string.format("<li>%s</li>", item_content))
    end
    return string.format("<ol>\n%s\n</ol>\n", table.concat(items, "\n"))
end

Writer.Block.CodeBlock = function(code)
    local attr = pandoc.utils.stringify(code.attr.identifier) ~= "" and
        ' id="' .. escape_html(pandoc.utils.stringify(code.attr.identifier)) .. '"' or ""
    local classes = #code.attr.classes > 0 and
        ' class="' .. table.concat(code.attr.classes, " ") .. '"' or ""
    local content = escape_html(code.text)
    return string.format("<pre%s%s><code>%s</code></pre>\n", attr, classes, content)
end

Writer.Block.Figure = function(figure)
    local anchor = get_anchor_if_id(figure)
    return {
        anchor,
        '<ac:structured-macro ac:name="align" ac:schema-version="1">',
        '<ac:parameter ac:name="align">center</ac:parameter><ac:rich-text-body>',
          '<ac:structured-macro ac:name="panel">\n',
          '<ac:parameter ac:name="bgColor">#FFFFFF</ac:parameter>\n',
          '<ac:parameter ac:name="title">\n',
          Writer.Blocks(figure.caption.long),
          '</ac:parameter>\n',
          '<ac:rich-text-body>\n',

          "<figure>\n",
          Writer.Blocks(figure.content),
          "</figure>\n",
          '</ac:rich-text-body>\n',
          '</ac:structured-macro>\n',
        '</ac:rich-text-body>\n',
        '</ac:structured-macro>\n',
    }
end

Writer.Inline.Image = function(image)
    --local attr = pandoc.utils.stringify(image.attr.identifier) ~= "" and
    --    ' id="' .. escape_html(pandoc.utils.stringify(image.attr.identifier)) .. '"' or ""
    --local classes = #image.attr.classes > 0 and
    --    ' class="' .. table.concat(image.attr.classes, " ") .. '"' or ""
    --local alt = pandoc.utils.stringify(image.attr.attributes["alt"] or image.caption) ~= "" and
    --    ' alt="' .. escape_html(pandoc.utils.stringify(image.attr.attributes["alt"] or image.caption)) .. '"' or ""
    --local title = pandoc.utils.stringify(image.attr.attributes["title"]) ~= "" and
    --    ' title="' .. escape_html(pandoc.utils.stringify(image.attr.attributes["title"])) .. '"' or ""
    local src = image.src -- escape_html(image.src)
    -- if the image has class thumbnail, set the width to 220 pixels, otherwise set it to 440 pixels
    local width = 440
    for _, class in ipairs(image.attr.classes) do
        if class == "thumbnail" then
            width = 220
            break
        end
    end
    return string.format('<ac:image ac:width="%d"><ri:attachment ri:filename="%s"/></ac:image>', width, src)
end

Writer.Block.RawBlock = function(raw)
    return raw.text .. "\n"
end

Writer.Block.BlockQuote = function(quote)
    return {
        "<blockquote>\n",
        Writer.Blocks(quote.content),
        "</blockquote>\n"
    }
end

process_table_cell = function(cell, cell_tag)
    local content = Writer.Blocks(cell.contents)
    return string.format("<%s>%s</%s>", cell_tag, content, cell_tag)
end

Writer.Block.Table = function(table_)
    -- process header
    local header_rows = {}
    for _, row in ipairs(table_.head.rows) do
        local row_cells = {}
        for _, cell in ipairs(row.cells) do
            local cell_content = process_table_cell(cell, "th")
            table.insert(row_cells, cell_content)
        end
        table.insert(header_rows, string.format("<tr>\n%s\n</tr>", table.concat(row_cells, "\n")))
    end
    -- process body
    local rows = {}
    for _, body in ipairs(table_.bodies) do
        for _, row in ipairs(body.body) do
            local row_cells = {}
            for _, cell in ipairs(row.cells) do
                local cell_content = process_table_cell(cell, "td")
                table.insert(row_cells, cell_content)
            end
            table.insert(rows, string.format("<tr>\n%s\n</tr>", table.concat(row_cells, "\n")))
        end
    end
    return string.format("<table><thead>\n%s\n</thead>\n<tbody>\n%s\n</tbody></table>\n",
        table.concat(header_rows, "\n"), table.concat(rows, "\n"))
end

Writer.Block.HorizontalRule = function()
    return "<hr/>\n"
end
