# SPDX-FileCopyrightText: <text>Copyright 2026 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
# SPDX-License-Identifier: MIT

TOOLS_ROOT := $(abspath $(CURDIR)/../..)
CONTENT_ROOT := $(CURDIR)

# We want to enable links to github issues and edit links to github for the
# HTML output of this example to demonstrate those features, so we set these
# variables.
HTML_ISSUE_LINKS = 1
HTML_EDIT_LINKS = 1

include $(TOOLS_ROOT)/Makefile
